apiVersion: batch/v1
kind: Job
metadata:
  name: $USER-$TS
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: magic
        image: robcurrie/ubuntu
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "1G"
          limits:
            cpu: "2"
            memory: "2G"
        # command: ["/bin/bash", "-c"]
        # args: ['for i in {1..100}; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
        command: ["python3", "run.py"]
        args: ["-c", "100", "foobar"]
      restartPolicy: Never
