apiVersion: v1
kind: Pod
metadata:
  name: $USER-pod
spec:
  containers:
  - name: $USER-container
    image: robcurrie/ubuntu
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["infinity"]
    env:
      - name: AWS_PROFILE
        value: "prp"
      - name: AWS_S3_ENDPOINT
        value: "https://s3.nautilus.optiputer.net"
    volumeMounts:
      - mountPath: /root/.aws
        name: credentials
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
  restartPolicy: Never
  volumes:
    - name: credentials
      secret:
        secretName: $USER-aws-credentials
